var parseConstants = {
    "PARSE_APPLICATION_ID": "TEDdEUZz4EKdPoByn5Zch6Mq4jX2b9Bwi60XmZcQ",
    "PARSE_REST_API_KEY": "uFNll3OexgfW71uKS6o3ovDoOm2OIZZXdNJD1QRt"
};
var NUMBER_OF_LAST_QUESTIONS_DEFAULT = 5;
var CHARACTERS_TO_BE_DISPLAYED_AT_SMALL_QUESTIONS = 20;